---
title: "Teaching"
output:
  html_document:
    theme: cosmo     # sleek Bootstrap theme
    highlight: tango # syntax highlighting
    toc: true
    toc_float: true
    number_sections: false
    df_print: paged
---

Professor Larson invites students not only to the “social facts” within criminology, but also the process and logic of social science that provides the scientific foundation for this knowledge. Dr. Larson has a passion for quantitative and statistical methods and works to convey these tools in an understandable and intuitive way. Through his teaching and collaborative research with students, he hopes students gain both substantive knowledge and methodological tools to help make sense of the social world, and their place within it, in order to become more responsibly engaged in society. Professor Larson teaches Theories of Criminal Behavior, Punishment, Corrections, & Society, Communities & Crime, Basic Quantitative Criminology & Statistics, and Research Methods and Data Analysis. He also directs Hamline’s Summer Collaborative Undergraduate Research program (SCUR), and leads the summer research seminar.

## Hamline University 
### Department of Criminal Justice \& Forensic Science

* CJFS 3735 Communities & Crime
  + Fall 2025 ([syllabus](syllabi/CJFS_3735_F25.pdf))

* CJFS 3770 Punishment, Corrections, and Society
  + Fall 2024 ([syllabus](syllabi/CJFS_3770_F24.pdf))
  + Fall 2023 ([syllabus](syllabi/CJFS_3770_F23.pdf))

* CJFS 1980 Basic Quantitative Criminology and Statistics
  + Spring 2023 ([syllabus](syllabi/CJFS_1980_S23.pdf))

* CJFS 3750 Theories of Criminal Behavior
  + Spring 2025 ([syllabus](syllabi/CJFS_3750_S25.pdf))
  + Spring 2024 ([syllabus](syllabi/CJFS_3750_S24.pdf))
  + Fall 2024 ([syllabus](syllabi/CJFS_3750_F24.pdf))
  + Spring 2023 ([syllabus](syllabi/CJFS_3750_S23.pdf))
  + Fall 2022 ([syllabus](syllabi/CJFS_3750_F22.pdf))
  
* CJFS 3140 Research Methods and Data Analysis
  + Fall 2025 ([syllabus](syllabi/CJFS 3140 F25 Syllabus.pdf))
  + Spring 2024 ([syllabus](syllabi/CJFS_3140_S24.pdf))
  + Fall 2023 ([syllabus](syllabi/CJFS_3140_F23.pdf))
  + Spring 2023 ([syllabus](syllabi/CJFS_3140_S23.pdf))
  + Fall 2022 ([syllabus](syllabi/CJFS_3140_F22.pdf))
  
* INDP 4015 SCUR: Summer Collaborative Undergraduate Research Seminar
  + Summer 2024, Summer 2025 ([syllabus](https://docs.google.com/document/d/1MKLlNHmP9oADG6uCbvaXZQuWEAGcJec_1pVg6phjwkg/edit?usp=sharing))

## University of Minnesota
### Department of Sociology

* Basic Social Statistics (UMN SOC 3811)
  + Spring 2022 ([syllabus](syllabi/larson_3811_22.pdf))

* Sociology of Neighborhoods (UMN SOC 3081) - Temporary
  + Spring 2017 

  

  