---
title: "Writing"
---

### Peer-Reviewed Articles

* N. Jeanie Santaularia, Ryan Larson, Christopher E. Robertson, Christopher Uggen. 2025. [“Mental Health Before and After George Floyd’s Murder in Minneapolis in Black, Latine, and White Communities.”](pubs/santaularia_etal_24_final.pdf) Forthcoming at *American Journal of Epidemiology*.

* Schwendeman, Hannah, Veronica L. Horowitz, Frank Edwards, Robert Stewart, Ryan Larson, and Christopher Uggen. 2024. ["'It's Two Separate Systems That..Keep You Under a Thumb': Dual Debt in the Child Support and Criminal Legal Systems."](pubs/schwendeman_etal_24.pdf). *Law and Society Review* 1-26. 

* Allison Lind, Ryan P. Larson, Susan M. Mason, Christopher Uggen. 2024. [“Carjacking and Homicide in Minneapolis After the Police Killing of George Floyd: Evidence from an Interrupted Time Series Analysis”](pubs/lind_etal_24.pdf)  *Social Science & Medicine* 358: 1-19. 

* Sarah Shannon, Ian Kennedy, Ryan Larson, Kate O’Neil, and Alexes Harris. 2024. [“Economic Extraction via the Criminal Legal System: A Community-level Perspective.”](pubs/shannon_etal_24.pdf)  *Socius* 10.

* Horowitz, Veronica, Ryan P. Larson, Robert Stewart, and Christopher Uggen. 2024. [“Fines, Fees, and Families: Monetary Sanctions as Stigmatized Intergenerational Exchange.”](pubs/horowitz_etal_24.pdf) *The Sociological Quarterly* 1-20.

* Ryan P. Larson, Jeanie Santaularia, and Christopher Uggen. 2023. [“Temporal and Spatial Shifts in Gun Violence, Before and After a Historic Police Killing in Minneapolis.”](pubs/larson_etal_23_online.pdf) *Spatial and Spatiotemporal Epidemiology* 100602.

* Veronica Horowitz, Kimberly Spencer-Suarez, Ryan Larson, Robert Stewart, Frank Edwards, Emmi Obara, and Christopher Uggen. 2022. ["Dual Debtors: Child Support and Criminal Financial Legal Obligations."](pubs/horowitz_etal_22.pdf) *Social Service Review*, 96(2):226-267.

* Amber Hamilton, Doug Hartmann, and Ryan P. Larson. 2022. [“Assessing and Extending Colorblind Racism Theory Using National Survey Data.”](pubs/hamilton_etal_22.pdf) *Sociology of Race and Ethnicity*, 8(2): 267-283.

* Veronica Horowitz, Ryan Larson, Victoria Piehowski, Allison Nobles, and Josh Page. 2021. [“Pragmatic Punitiveness: The Institutionalization of Criminal Domestic Violence Protection Orders.”](pubs/horowitz_etal_21.pdf) Forthcoming at *Social & Legal Studies*.

* Rob Stewart, Bieanna Watters, Veronica Horowitz, Ryan Larson, Brian Sargent, and Christopher Uggen. 2022. [“Native Americans and Monetary Sanctions."](pubs/stewart_etal_22.pdf) *The Russell Sage Foundation Journal of the Social Sciences* 8(2), 137-156.

* Ryan P. Larson, Sarah Shannon, Aaron Sojourner, and Chris Uggen. 2021. ["Felony History and Change in U.S. Employment Rates."](pubs/larson_etal_22.pdf) *Social Science Research* 103 102649. 

* Jeanie Santaularia, Ryan P. Larson, and Christopher Uggen. 2021. [“Criminal Punishment, Child Abuse, and Violent
Injury in Minnesota.”](pubs/santaularia_etal_21.pdf) *Injury Epidemiology*, 8(11): 1-10.

* Stewart, Evan, Penny Edgell, Sarah-Catherine Billups, and Ryan Larson. 2019. [“The Stakes of Symbolic Boundaries.”](pubs/stewart_etal_19.pdf)
*The Sociological Quarterly*, 61(2): 309-333.

* Ann Meier, Ben Hartmann, and Ryan Larson. 2018. [“A Quarter Century of Youth Activity Participation: Inequalities by Race, Class, Gender and Age?”](pubs/meier_etal_18.pdf). *Journal of Youth and Adolescence* 47(6): 1299-1316.

* Larson, Ryan P. and Andrew Lindner. 2018. [“Professionalization Through Attrition?: An Event History Analysis of Mortalities in Citizen Journalism.”](pubs/larson_lindner_18.pdf) *Information, Communication, and Society* 21(5): 746-760.

* Lindner, Andrew and Ryan P. Larson. 2017. [“The Expansion and Contraction of the Journalistic Field and American Online Citizen Journalism, 2000-2012”](pubs/lindner_larson_17.pdf). *Poetics* 64: 40-52.

* Hartmann, Doug, Paul Croll, Ryan Larson, Joseph Gerteis, and Alex Manning. 2017. [“Colorblindness as Identity: Key Determinants, Relations to Ideology, and Implications for Attitudes about Race and Policy”](pubs/hartmann_etal_17.pdf).
*Sociological Perspectives* 60(5): 866-888.

* Hawkins, Daniel, Andrew Lindner, Ryan Larson, and Johnathan Santos. 2015. [“Overrating Bruins, Underrating Badgers: Media, Prestige, and College Basketball Rankings.”](pubs/hawkins_etal_15.pdf) *Journal of Sports Management and Commercialization*
6(3): 11-26.

### Papers Under Review

* Christopher Uggen, Carsyn Schneider, Ryan Larson, Robert Stewart. ``Democratic Expansion? Restoring the Vote to People on Probation and Parole in the United States, 1964-2023." Under review at *Criminology*.

* Ryan Larson. ``The Causal Packaging Effects of Punishment." Revise and resubmit at *Journal of Quantitative Criminology*. 

* Ryan P. Larson, Jillian Peterson, James Densley, Jaycee Manchi, N. Jeanie Santaularia, Christopher Uggen,
and Christopher E. Robertson. ”The Changing Nature of Homicide in the Twin Cities Before, During, and
After the Pandemic and the Murder of George Floyd.” Under Review at *Journal of Quantitative Criminology*.

Maryam Tanveer, Ryan Larson, N. Jeanie Santaularia, Christopher Robertson, and Christopher Uggen. “Temporal Exposure to Police-Involved Shootings and the Incidence of Mental Health Conditions in Minneapolis, Minnesota.” Under review at *Journal of Urban Health*.

Ryan P. Larson, Robert Stewart, Veronica Horowitz, and Christopher Uggen. “The Racialized Packaging of
Punishment: An Instrumental Variables Approach to Confinement, Surveillance, and Financial Extraction.”
Under review at *Criminology*.

### Technical Reports

* Uggen, Christopher, Ryan Larson, Sarah Shannon, Robert Stewart, and Molly Hauf. 2024. ["Locked Out 2024: Four Million Denied Voting Rights Due to a Felony Conviction"](https://www.sentencingproject.org/app/uploads/2024/10/Locked-Out-2024-Four-Million-Denied-Voting-Rights-Due-to-a-Felony-Conviction.pdf) Washington, D.C.: The Sentencing Project.

* Uggen, Christopher, Ryan Larson, Sarah Shannon, and Robert Stewart. 2022. ["Locked Out 2022: Estimates of People Denied Voting Rights Due to a Felony Conviction"](https://www.sentencingproject.org/app/uploads/2024/03/Locked-Out-2022-Estimates-of-People-Denied-Voting.pdf) Washington, D.C.: The Sentencing Project.

* Uggen, Christopher, Ryan Larson, Sarah Shannon, and Arleth Pulido-Nava. 2020. ["Locked Out 2020: Estimates of People Denied Voting Rights Due to a Felony Conviction"](https://www.sentencingproject.org/wp-content/uploads/2020/10/Locked-Out-2020.pdf) Washington, D.C.: The Sentencing Project.

* Uggen, Christopher, Ryan Larson, and Sarah Shannon. 2016. ["6 Million Lost Voters: State-Level Estimates of Felony Disenfranchisement, 2016"](https://www.sentencingproject.org/wp-content/uploads/2016/10/6-Million-Lost-Voters.pdf) Washington, D.C.: The Sentencing Project.

### Book Chapters

* Christopher Uggen, Ryan Larson, Sarah Shannon, and Robert Stewart. 2023. [“The Denial of Voting Rights to People with Criminal Records."](pubs/uggen_etal_23.pdf) *Social Problems in an Age of Mass Incarceration.* Edited by Kristen M. Budd, David Lane, Glenn Muschert, and Jason Smith. Society for the Study of Social Problems (SSSP).

* Larson, Ryan P.. 2020. [“Felon Disenfranchisement.”](pubs/larson_19.pdf) *Voting and Political Representation in America: Issues and Trends*, edited by Mark P. Jones. Santa Barbara, CA: ABC-CLIO.

* Andrew Lindner and Ryan P. Larson. 2018. [“Regression Analysis.”](pubs/lindner_larson_18.pdf) *Encyclopedia of Sociology*, edited by George
Ritzer. Oxford: Wiley-Blackwell.

* Larson, Ryan P. and Chris Uggen. 2017. [“Felon Disenfranchisement.”](pubs/uggen_larson_17.pdf) *Encyclopedia of Corrections*, edited by
Kent R. Kerley. Oxford: Wiley-Blackwell.

### Other Writing

* Remington, Katie, Ryan Larson, and Molly Hauf. 2023. “The Status Quo of Financial-Based Driver’s License Suspensions in Minnesota.” Forthcoming from the *Minnesota Justice Research Center*.

* Uggen, Christopher and Ryan P. Larson. 2017. [“Is The Public Getting Smarter on Crime?”](pubs/uggen_larson_contexts_17.pdf) *Contexts* Fall 2017.

* Lindner, Andrew and Ryan P. Larson. 2016. [“The Year English Soccer Wasn’t For Sale.”](pubs/lindner_larson_contexts_16.pdf) Contexts Fall 2016.

* A collection of contributions to [*The Society Pages*](https://thesocietypages.org/) can be found [here](https://thesocietypages.org/search/ryan%20larson/).


